  insert into honey values(#{mnum} , #{id} , #{nic} , numUp.nextval , #{title} , 0 ,#{content},0 ,0 , sysdate ,#{pass})

  CREATE TABLE "SCOTT"."HONEY" 
   (	"MNUM" NUMBER(20,0), 
	"ID" VARCHAR2(255 BYTE), 
	"NIC" VARCHAR2(255 BYTE), 
	"WNUM" NUMBER(20,0), 
	"TITLE" VARCHAR2(255 BYTE), 
	"COMP" NUMBER(20,0), 
	"CONTENT" VARCHAR2(4000 BYTE), 
	"GOOD" NUMBER(20,0), 
	"CLICK" NUMBER(20,0), 
	"DDAY" DATE, 
	"PASS" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
REM INSERTING into SCOTT.HONEY
SET DEFINE OFF;
drop table honey;


numUp --- 꿀단지 게시물 번호 시퀀스
CREATE SEQUENCE numUp
INCREMENT BY 1;

drop sequence numUp;
select * from suggestion;
select * from honey;
select * from member;

  ALTER TABLE "SCOTT"."HONEY" ADD FOREIGN KEY ("MNUM")
	  REFERENCES "SCOTT"."MEMBER" ("MNUM") ENABLE;
